import { useAuthStore } from "@/store/auth";

export const useAuth = () => {
  const {
    hasHydrated,
    setHasHydrated,
    user,
    token,
    isAuthenticated,
    isLoading,
    error,
    requiresOtp,
    tempEmail,
    referralSource,
    referralCode,
    login,
    register,
    verifyOtp,
    resendOtp,
    forgotPassword,
    resetPassword,
    changePassword,
    googleLogin,
    appleLogin,
    devLogin,
    logout,
    clearError,
    setUser,
    setToken,
    clearTempEmail,
    setReferralInfo,
    clearReferralInfo,
    selectedRole,
    setSelectedRole,
    hasSeenOnboarding,
    setHasSeenOnboarding,
    forceLogout,
    setForceLogout,
  } = useAuthStore();

  return {
    hasHydrated,
    setHasHydrated,
    user,
    token,
    isAuthenticated,
    isLoading,
    error,
    requiresOtp,
    tempEmail,
    referralSource,
    referralCode,
    login,
    register,
    verifyOtp,
    resendOtp,
    forgotPassword,
    resetPassword,
    changePassword,
    googleLogin,
    appleLogin,
    devLogin,
    logout,
    clearError,
    setUser,
    setToken,
    clearTempEmail,
    setReferralInfo,
    clearReferralInfo,
    selectedRole,
    setSelectedRole,
    hasSeenOnboarding,
    setHasSeenOnboarding,
    forceLogout,
    setForceLogout,
  };
};
