export interface NigerianBank {
  name: string;
  code: string;
  slug: string;
}

export const NIGERIAN_BANKS: NigerianBank[] = [
  { name: "Access Bank", code: "044", slug: "access-bank" },
  { name: "Access Diamond Bank", code: "063", slug: "access-diamond" },
  { name: "ALAT by Wema", code: "035A", slug: "alat" },
  { name: "ASO Savings and Loans", code: "401", slug: "aso" },
  { name: "Bowen Microfinance Bank", code: "509", slug: "bowen" },
  { name: "Carbon", code: "565", slug: "carbon" },
  { name: "Citibank Nigeria", code: "023", slug: "citibank" },
  { name: "Ecobank Nigeria", code: "050", slug: "ecobank" },
  { name: "Ekondo Microfinance Bank", code: "562", slug: "ekondo" },
  { name: "Fidelity Bank", code: "070", slug: "fidelity" },
  { name: "First Bank of Nigeria", code: "011", slug: "first-bank" },
  { name: "First City Monument Bank (FCMB)", code: "214", slug: "fcmb" },
  { name: "Globus Bank", code: "001", slug: "globus" },
  { name: "GoMoney", code: "100022", slug: "gomoney" },
  { name: "GTBank (Guaranty Trust Bank)", code: "058", slug: "gtbank" },
  { name: "Heritage Bank", code: "030", slug: "heritage" },
  { name: "Jaiz Bank", code: "301", slug: "jaiz" },
  { name: "Keystone Bank", code: "082", slug: "keystone" },
  { name: "Kuda Bank", code: "502", slug: "kuda" },
  { name: "Lotus Bank", code: "303", slug: "lotus" },
  { name: "Mint Finex MFB", code: "507", slug: "mint" },
  { name: "Moniepoint MFB", code: "505", slug: "moniepoint" },
  { name: "OPay", code: "999", slug: "opay" },
  { name: "Paga", code: "114", slug: "paga" },
  { name: "Palmpay", code: "108", slug: "palmpay" },
  { name: "Polaris Bank", code: "076", slug: "polaris" },
  { name: "Providus Bank", code: "101", slug: "providus" },
  { name: "Rubies MFB", code: "125", slug: "rubies" },
  { name: "Sparkle Bank", code: "513", slug: "sparkle" },
  { name: "Stanbic IBTC Bank", code: "221", slug: "stanbic" },
  { name: "Standard Chartered Bank", code: "068", slug: "standard-chartered" },
  { name: "Sterling Bank", code: "232", slug: "sterling" },
  { name: "Suntrust Bank", code: "100001", slug: "suntrust" },
  { name: "TAJ Bank", code: "302", slug: "taj" },
  { name: "Titan Bank", code: "102", slug: "titan" },
  { name: "UBA (United Bank for Africa)", code: "033", slug: "uba" },
  { name: "Union Bank of Nigeria", code: "032", slug: "union-bank" },
  { name: "Unity Bank", code: "215", slug: "unity" },
  { name: "VFD MFB", code: "566", slug: "vfd" },
  { name: "Wema Bank", code: "035", slug: "wema" },
  { name: "Zenith Bank", code: "057", slug: "zenith" },
];
